
#
# Makefile
#
# EE 312
# Assignment9
#

all: assignment9

assignment9: polynomial.cpp functions.cpp main.cpp
	g++ -ggdb polynomial.cpp functions.cpp main.cpp -o assignment9

clean:
	rm -f *.o a.out core assignment9
